// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2y171hYvhp1RbJ_XYPgMqfrbj43B6Ol4',
    appId: '1:700748988222:web:16f145565b50a0dc13b66f',
    messagingSenderId: '700748988222',
    projectId: 'projectakhirpamulti',
    authDomain: 'projectakhirpamulti.firebaseapp.com',
    storageBucket: 'projectakhirpamulti.firebasestorage.app',
    measurementId: 'G-HB9SQNMPKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB04tr1nQb6YfEdJXr7lwC7nbytov7tY2k',
    appId: '1:700748988222:android:70b8d2bd3cf4249f13b66f',
    messagingSenderId: '700748988222',
    projectId: 'projectakhirpamulti',
    storageBucket: 'projectakhirpamulti.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWb0XvLbJz5W74XbEPbukJBljQRRVMzUc',
    appId: '1:700748988222:ios:e90932b76afc203d13b66f',
    messagingSenderId: '700748988222',
    projectId: 'projectakhirpamulti',
    storageBucket: 'projectakhirpamulti.firebasestorage.app',
    iosClientId: '700748988222-5v8p5p3m3kout97hmkag8t8c48b6lkkk.apps.googleusercontent.com',
    iosBundleId: 'com.example.appResepMakanan',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWb0XvLbJz5W74XbEPbukJBljQRRVMzUc',
    appId: '1:700748988222:ios:e90932b76afc203d13b66f',
    messagingSenderId: '700748988222',
    projectId: 'projectakhirpamulti',
    storageBucket: 'projectakhirpamulti.firebasestorage.app',
    iosClientId: '700748988222-5v8p5p3m3kout97hmkag8t8c48b6lkkk.apps.googleusercontent.com',
    iosBundleId: 'com.example.appResepMakanan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2y171hYvhp1RbJ_XYPgMqfrbj43B6Ol4',
    appId: '1:700748988222:web:5f234afc58840ced13b66f',
    messagingSenderId: '700748988222',
    projectId: 'projectakhirpamulti',
    authDomain: 'projectakhirpamulti.firebaseapp.com',
    storageBucket: 'projectakhirpamulti.firebasestorage.app',
    measurementId: 'G-H987YH0NYP',
  );

}